application: grosharies-site
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /default
  script: web.pages.default.app
  
- url: /index
  script: web.pages.index.app
  
- url: /FAQ
  script: web.pages.FAQ.app

- url: /createList
  script: web.pages.createList.app
 
- url: /newList
  script: web.pages.newList.app
  
- url: /manageList
  script: web.pages.manageList.app
  
- url: /getAllGroups
  script: web.pages.getAllGroups.app

- url: /newGroup
  script: web.pages.newGroup.app

- url: /logout
  script: web.pages.logout.app

- url: /createGroup
  script: web.pages.createGroup.app 

- url: /list
  script: web.pages.list.app
  
- url: /about
  script: web.pages.about.app

- url: /contact
  script: web.pages.contact.app
  
- url: /terms
  script: web.pages.terms.app
  
- url: /privacy
  script: web.pages.privacy.app
  
- url: /listPage
  script: web.pages.listPage.app

- url: /productsList
  script: web.pages.productsList.app
 
- url: /search
  script: web.pages.search.app

- url: /googleLogin
  script: web.pages.googleLogin.app
  
- url: /static
  static_dir: web/static

- url: /
  script: web.pages.default.app
  
- url: /api/(.*)
  script: api.\1.app

- url: /(.*)
  script: web.pages.\1.app
  


libraries:
- name: webapp2
  version: "2.5.2"
